import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("places", "routes/place-list.tsx"),
  route("maps/:categorySlug", "routes/map-category.tsx"),
  route("places/:placeSlug", "routes/place-detail.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("me", "routes/me.tsx"),
  route("suggestions/new", "routes/place-suggest.tsx"),
  route("me/suggestions", "routes/my-suggestions.tsx"),
  route("corrections/new", "routes/place-correction.tsx"),
  route("corrections/verify", "routes/verify-correction.tsx"),
  route("reviewer/apply", "routes/reviewer-apply.tsx"),
  route("reviewer/ratings", "routes/reviewer-ratings.tsx"),
  route("reviewers/:slug", "routes/reviewer-profile.tsx"),
  route("logout", "routes/logout.tsx"),
  route("admin/places", "routes/admin-places.tsx"),
  route("admin/import", "routes/admin-import.tsx"),
  route("admin/candidates", "routes/admin-candidates.tsx"),
  route("admin/candidates/bulk", "routes/admin-candidates-bulk.tsx"),
  route("admin/data-sync", "routes/admin-data-sync.tsx"),
  route("admin/reviewers", "routes/admin-reviewers.tsx"),
  route("admin/ratings", "routes/admin-ratings.tsx"),
  route("admin/place-operations", "routes/admin-place-operations.tsx"),
] satisfies RouteConfig;
