import { env } from "cloudflare:workers";
import { Form, Link } from "react-router";
import type { Route } from "./+types/admin-operations";
import { createDb } from "../db/client.server";
import { requireAdmin } from "../features/auth/session.server";
import { resolveOperationalAlert } from "../features/operations/alerts.server";
import { getOperationalDashboard } from "../features/operations/dashboard.server";

export async function loader({ request }: Route.LoaderArgs) { await requireAdmin(request); return getOperationalDashboard(createDb(env.DB), { now: new Date().toISOString() }); }
export async function action({ request }: Route.ActionArgs) { const admin = await requireAdmin(request); const form = await request.formData(); await resolveOperationalAlert(createDb(env.DB), { alertId: String(form.get("alertId")), actorUserId: admin.id, note: String(form.get("note") ?? ""), now: new Date().toISOString() }); return { message: "알림을 해결 처리했습니다." }; }
export function meta() { return [{ title: "운영 현황 — Re:Taste Admin" }]; }
export default function AdminOperations({ loaderData, actionData }: Route.ComponentProps) { return <main id="main" className="admin-rating-shell"><header><p className="eyebrow">ADMIN / OPERATIONS</p><h1>운영 현황</h1><p>실제 D1 실행 이력으로 수집·검수·AI·실패 상태를 확인합니다. 외부 이메일 알림은 운영 문의 주소 확정 후 연결합니다.</p><Link to="/admin/candidates">후보 검수로 이동</Link></header>{actionData?.message && <p className="admin-notice">{actionData.message}</p>}<section className="ops-dashboard-grid">{loaderData.windows.map((item) => <article key={item.label}><h2>{item.label}</h2><dl><div><dt>신규 후보</dt><dd>{item.candidates}</dd></div><div><dt>승인 / 반려</dt><dd>{item.approvals} / {item.rejections}</dd></div><div><dt>AI 성공 / 실패</dt><dd>{item.aiSuccess} / {item.aiFailed}</dd></div><div><dt>AI 캐시</dt><dd>{item.aiCached}</dd></div><div><dt>동기화 / 재계산 실패</dt><dd>{item.syncFailed} / {item.recomputeFailed}</dd></div></dl></article>)}</section><section className="admin-rating-section"><h2>누락</h2><p>좌표 없는 영업 후보 <strong>{loaderData.missingCoordinates}</strong>곳</p></section><section className="admin-rating-section"><h2>열린 운영 알림</h2>{loaderData.alerts.length ? loaderData.alerts.map((alert) => <article className="integrity-case" key={alert.id}><div><strong>{alert.severity} · {alert.alertType}</strong><p>{alert.message}</p><small>{alert.occurrenceCount}회 · {alert.lastOccurredAt}</small><code>{alert.detailsJson}</code></div><Form method="post"><input type="hidden" name="alertId" value={alert.id}/><input name="note" placeholder="해결 근거" required/><button>해결 처리</button></Form></article>) : <p>열린 알림이 없습니다.</p>}</section></main>; }
