import { env } from "cloudflare:workers";
import { Form, Link, redirect } from "react-router";
import type { Route } from "./+types/me";
import { createDb } from "../db/client.server";
import { requireUser } from "../features/auth/session.server";
import { listMemberTaste } from "../features/members/member.server";
import { setSaved } from "../features/saves/save.server";
import { getMemberTasteGraph } from "../features/ratings/flavor-print.server";
export async function loader({ request }: Route.LoaderArgs) { const user = await requireUser(request); const db = createDb(env.DB); return { user, ...(await listMemberTaste(db, user.id)), tasteGraph: await getMemberTasteGraph(db, user.id) }; }
export async function action({ request }: Route.ActionArgs) { const user = await requireUser(request); const form = await request.formData(); await setSaved(createDb(env.DB), { userId: user.id, placeId: String(form.get("placeId") ?? ""), saved: false, now: new Date().toISOString() }); return redirect("/me"); }
export default function Me({ loaderData }: Route.ComponentProps) { return <main id="main" className="shell py-14"><p className="eyebrow">MY TASTE LOG</p><div className="flex flex-col gap-3 border-b border-neutral-300 pb-7 md:flex-row md:items-end md:justify-between"><div><h1 className="text-4xl font-semibold tracking-tight">{loaderData.user.displayName}님의 취향</h1><span className="mt-2 block text-sm font-normal text-neutral-500">{loaderData.user.email}</span></div><Link className="border border-neutral-900 px-4 py-2 text-sm font-medium" to="/reviewer/apply">리뷰어 신청·상태</Link></div><section className="taste-graph"><h2>나의 취향 그래프</h2>{loaderData.tasteGraph.status === "VISIBLE" ? loaderData.tasteGraph.dimensions.map((dimension) => <div key={dimension.key}><span>{dimension.key}</span><meter min="1" max="5" value={dimension.value}/><strong>{dimension.value.toFixed(1)}</strong></div>) : <p>학습 중 · Flavor Print가 있는 추천 장소 {loaderData.tasteGraph.placeCount}/5</p>}</section><div className="mt-8 grid gap-6 md:grid-cols-2"><TasteSection title="저장한 장소" count={loaderData.saved.length}>{loaderData.saved.map((place) => <article className="border-b border-neutral-200 py-4" key={place.id}><Link className="font-medium" to={`/places/${place.slug}`}>{place.name}</Link><p className="mt-1 text-sm font-normal text-neutral-500">{place.categoryEmoji} {place.categoryName} · {place.neighborhood}</p><Form method="post" className="mt-2"><input type="hidden" name="placeId" value={place.id}/><button className="text-xs font-medium text-emerald-800 underline">저장 해제</button></Form></article>)}{!loaderData.saved.length && <Empty text="지도에서 다시 보고 싶은 장소를 저장해 보세요." />}</TasteSection><TasteSection title="내가 평가한 장소" count={loaderData.rated.length}>{loaderData.rated.map((place) => <article className="border-b border-neutral-200 py-4" key={place.id}><Link className="font-medium" to={`/places/${place.slug}`}>{place.name}</Link><p className="mt-1 text-sm font-normal text-neutral-500">{place.categoryEmoji} {place.categoryName} · {place.neighborhood}</p><strong className={`mt-2 block text-xs font-medium ${place.value === 1 ? "text-emerald-800" : "text-red-700"}`}>{place.value === 1 ? "추천했어요" : "비추천했어요"}</strong></article>)}{!loaderData.rated.length && <Empty text="방문한 장소에 추천 또는 비추천을 남겨보세요." />}</TasteSection></div></main>; }
function TasteSection({ title, count, children }: { title: string; count: number; children: React.ReactNode }) { return <section className="border border-neutral-300 bg-white p-5"><header className="flex justify-between border-b border-neutral-300 pb-3"><h2 className="text-lg font-semibold">{title}</h2><span className="text-sm text-neutral-500">{count}곳</span></header>{children}</section>; }
function Empty({ text }: { text: string }) { return <p className="py-10 text-center text-sm font-normal text-neutral-500">{text}</p>; }
