import { env } from "cloudflare:workers";
import { Form, Link } from "react-router";
import type { Route } from "./+types/place-list";
import { PlaceCard } from "../components/places/PlaceCard";
import { createDb } from "../db/client.server";
import { parseMapState } from "../features/maps/map-state";
import { listPlaces, listPublicCategoryGroups } from "../features/places/place.server";
export async function loader({ request }: Route.LoaderArgs) { const url = new URL(request.url); const state = parseMapState(url.search); const category = url.searchParams.get("category") || undefined; const db = createDb(env.DB); const [places, groups] = await Promise.all([listPlaces(db, { categorySlug: category, query: state.query, bbox: state.bbox }), listPublicCategoryGroups(db)]); const selected = groups.flatMap((group) => group.children).find((child) => child.slug === category); return { places, state, category: selected ?? null, search: url.search }; }
export default function PlaceList({ loaderData }: Route.ComponentProps) { return <main id="main" className="shell py-12"><div className="flex flex-col gap-5 border-b-2 border-neutral-950 pb-7 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">NEARBY / PLACE LIST</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{loaderData.category ? `${loaderData.category.emoji} ${loaderData.category.name}` : "현재 지도 장소"}</h1><p className="mt-2 text-sm font-normal text-neutral-500">검수 승인된 영업 장소만 표시합니다.</p></div><Link className="border border-neutral-950 px-4 py-3 text-sm font-medium" to={`/${loaderData.search}`}>지도 보기</Link></div><Form className="mt-6 flex max-w-lg border border-neutral-300 bg-white"><input className="min-w-0 flex-1 px-4 py-3" name="q" defaultValue={loaderData.state.query} placeholder="목록에서 검색"/><input type="hidden" name="category" value={loaderData.category?.slug ?? ""}/><input type="hidden" name="bbox" value={loaderData.state.bbox.join(",")}/><button className="bg-neutral-950 px-4 text-white">찾기</button></Form><p className="mt-8 text-xs font-medium text-neutral-500">{loaderData.places.length} PLACES</p><div className="mt-3 grid grid-cols-1 gap-px bg-neutral-300 border-b border-neutral-300 md:grid-cols-3 xl:grid-cols-4">{loaderData.places.map((place) => <PlaceCard place={place} key={place.id}/>)}</div>{!loaderData.places.length && <p className="border border-neutral-300 py-16 text-center text-sm text-neutral-500">이 조건에서 공개된 장소를 찾지 못했어요.</p>}</main>; }
